spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: ture
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        legacy_limit_handler: true
    open-in-view: true
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/xquare_infra}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/xquareinfra}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 400
      minimum-idle: 100
      connection-timeout: 2000
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoint:
    health:
      show-details: always

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

github:
  token: ${GITHUB_TOKEN}
  url: https://api.github.com
logging:
  level:
    root: info

jwt:
  secret-key: ${JWT_SECRET_KEY:asdjfklasdjkflasjdklf}
  access-expired-exp: ${JWT_ACCESS_EXP:7200000}
  refresh-expired-exp: ${JWT_REFRESH_EXP:604800000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }

server:
  tomcat:
    max-connections: 200
    accept-count: 100
    connection-timeout: 20000
  domain:
    front-domain: ${FRONT_LOCAL:http://localhost:3000}
    back-domain: ${BACK_LOCAL:http://localhost:8080}
  port: ${SERVER_PORT:8080}

url:
  deploy: ${DEPLOY_URL}
  log: ${LOG_URL}
  gocd: ${GOCD_URL}
  cloudflare: ${CLOUDFLARE_URL}
  prometheus: ${PROMETHEUS_URL}

secret:
  projectSecret: ${PROJECT_SECRET}

vault:
  address: ${VAULT_URL}
  vaultToken: ${VAULT_TOKEN}

xquare:
  accessKey: ${XQUARE_ACCESS}
  secretKey: ${XQUARE_SECRET}
  gatewayDns: ${GATEWAY_DNS}

kubernetes:
  kubeConfig: ${KUBE_CONFIG}

cloudflare:
  zoneId: ${ZONE_ID}
  xAuthKey: ${X_AUTH_KEY}
  xAuthEmail: ${X_AUTH_EMAIL}

gocd:
  username: ${GOCD_USERNAME}
  password: ${GOCD_PASSWORD}

datadog:
  api-key: ${DATADOG_API_KEY}
  app-key: ${DATADOG_APP_KEY}