spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: ture
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        legacy_limit_handler: true
    open-in-view: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/xquareinfra}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoint:
    health:
      show-details: always

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

github:
  token: ${GITHUB_TOKEN}
  url: https://api.github.com
logging:
  level:
    root: info

jwt:
  secret-key: ${JWT_SECRET_KEY:asdjfklasdjkflasjdklf}
  access-expired-exp: ${JWT_ACCESS_EXP:7200000}
  refresh-expired-exp: ${JWT_REFRESH_EXP:604800000}
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 10000
    connection-timeout: 20000
  domain:
    front-domain: ${FRONT_LOCAL:http://localhost:3000}
    back-domain: ${BACK_LOCAL:http://localhost:8080}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /xquare-infra

url:
  deploy: ${DEPLOY_URL}
  log: ${LOG_URL}

secret:
  projectSecret: ${PROJECT_SECRET}

vault:
  address: ${VAULT_URL}
  vaultToken: ${VAULT_TOKEN}

xquare:
  accessKey: ${XQUARE_ACCESS}
  secretKey: ${XQUARE_SECRET}

kubernetes:
  kubeConfig: ${KUBE_CONFIG}